In [1]:
import os 
import sys
import pandas as pd
import numpy as np
import confix
from sklearn import preprocessing
import time
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
#import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf


# Predictor 



In [2]:
# Combine all PDBs into a single dataframe
dfs = []
for filename in os.listdir(confix.PATH_FEATURES_RING):
    dfs.append(pd.read_csv(confix.PATH_FEATURES_RING + filename, sep='\t'))
df = pd.concat(dfs)


In [3]:
print(f'len of the data frame: {len(df)}')
df.head(10).T

len of the data frame: 735510


0      1      2      3      4      5      6      7      8  \
pdb_id        2ia7   2ia7   2ia7   2ia7   2ia7   2ia7   2ia7   2ia7   2ia7   
s_ch             A      A      A      A      A      A      A      A      A   
s_resi          43    100    101     94     70     33    100     95    108   
s_ins                                                                        
s_resn           T      E      A      V      T      I      E      T      I   
s_ss8            -      T      G      E      H      H      T      E      E   
s_rsa         0.07   0.34  0.396   0.07  0.099  0.006   0.34   0.43    0.0   
s_up          18.0   13.0    5.0   16.0   12.0   18.0   13.0   10.0   21.0   
s_down        10.0    5.0   13.0   14.0   10.0   11.0    5.0   22.0   14.0   
s_phi        -1.96 -1.992 -1.028 -2.293 -1.011 -1.103 -1.992 -2.322 -1.776   
s_psi        2.182  0.369 -0.615  2.033 -0.687 -0.817  0.369   2.27  1.952   
s_ss3            H      H      H      H      H      H      H      H      H   
s_a1        -0.032  1.357 -0.591 -1.337 -0.032 -1.239  1.357 -0.032 -1.239   
s_a2         0.326 -1.453 -1.302 -0.279  0.326 -0.547 -1.453  0.326 -0.547   
s_a3         2.213  1.477 -0.733 -0.544  2.213  2.131  1.477  2.213  2.131   
s_a4         0.908  0.113   1.57  1.242  0.908  0.393  0.113  0.908  0.393   
s_a5         1.313 -0.837 -0.146 -1.262  1.313  0.816 -0.837  1.313  0.816   
t_ch             A      A      A      A      A      A      A      A      A   
t_resi          56    103    104    109     74     89    107    107    125   
t_ins                                                                        
t_resn           C      E      G      D      I      I      L      L      Y   
t_ss8            -      G      T      E      H      E      E      E      E   
t_rsa          0.0    0.5  0.298  0.178   0.03  0.047  0.049  0.049  0.153   
t_up          20.0    7.0    4.0    7.0   20.0   24.0   10.0   10.0   19.0   
t_down        15.0    7.0   12.0   20.0   15.0    8.0   18.0   18.0   11.0   
t_phi       -2.133 -1.707  1.326  -1.54 -1.051 -2.101 -1.758 -1.758 -1.889   
t_psi        2.294  0.184  0.494  2.026 -0.793  2.734  2.298  2.298  2.084   
t_ss3            H      H      L      H      H      H      H      H      H   
t_a1        -1.343  1.357 -0.384   1.05 -1.239 -1.239 -1.019 -1.019   0.26   
t_a2         0.465 -1.453  1.652  0.302 -0.547 -0.547 -0.987 -0.987   0.83   
t_a3        -0.862  1.477   1.33 -3.656  2.131  2.131 -1.505 -1.505  3.097   
t_a4         -1.02  0.113  1.045 -0.259  0.393  0.393  1.266  1.266 -0.838   
t_a5        -0.255 -0.837  2.064 -3.242  0.816  0.816 -0.912 -0.912  1.512   
Interaction  HBOND  HBOND  HBOND    NaN  HBOND    VDW    VDW    NaN  HBOND   

                 9  
pdb_id        2ia7  
s_ch             A  
s_resi          72  
s_ins               
s_resn           G  
s_ss8            H  
s_rsa        0.214  
s_up           3.0  
s_down        18.0  
s_phi       -1.112  
s_psi       -0.657  
s_ss3            H  
s_a1        -0.384  
s_a2         1.652  
s_a3          1.33  
s_a4         1.045  
s_a5         2.064  
t_ch             A  
t_resi          76  
t_ins               
t_resn           N  
t_ss8            H  
t_rsa        0.465  
t_up           5.0  
t_down        20.0  
t_phi       -1.395  
t_psi       -0.425  
t_ss3            H  
t_a1         0.945  
t_a2         0.828  
t_a3         1.299  
t_a4        -0.169  
t_a5         0.933  
Interaction  HBOND

![DATA TABLE](data/images/table_data.png)

In [25]:
def drop_cols(df):
    df = df.dropna(inplace=True)

def Y_to_categorical(df):
    Y = df['Interaction'].astype('category')
    return Y

def transform_alphabetical_numerical(df):
    list = ['s_ch', 's_resn', 's_ss8', 's_ss3', 't_ch', 't_resn', 't_ss8', 't_ss3']
    label_encoder = preprocessing.LabelEncoder()
    for i in list:
        df[i] = label_encoder.fit_transform(df[i])

def create_X(df):
    df = df.drop(['Interaction', 's_ins', 't_ins', 'pdb_id'], axis=1)
    df = df.astype(float)
    X = df.rank(method='average', pct = True).round(1).astype('category') #pct = True
    return X

In [26]:
drop_cols(df)
Y = Y_to_categorical(df)
transform_alphabetical_numerical(df)
X = create_X(df)

In [27]:
X.head(10).T

0         1         2         4         5         6         8   \
s_resi   60960.5  148470.5  149927.5  103582.5   44976.0  148470.5  160017.0   
s_resn  373766.0   84741.5   16697.5  373766.0  172071.5   84741.5  172071.5   
s_ss8    36419.0  442672.5  181340.5  296138.5  296138.5  442672.5  125776.5   
s_rsa   199228.5  347413.5  369748.0  222250.0  102710.5  347413.5   45540.5   
s_up    268635.0  163592.0   40764.5  145442.5  268635.0  163592.0  341384.5   
s_down   47212.0    5511.5  110725.5   47212.0   65361.5    5511.5  137129.5   
s_phi    89267.5   84962.5  383472.0  396705.0  302828.5   84962.5  113889.0   
s_psi   333438.0  277154.5  203781.0  164812.0   49737.5  277154.5  309090.5   
s_ss3   219852.0  219852.0  219852.0  219852.0  219852.0  219852.0  219852.0   
s_a1    241426.0  393375.5  171500.5  241426.0   49750.5  393375.5   49750.5   
s_a2    329883.0   23634.5   54607.5  329883.0  176457.5   23634.5  176457.5   
s_a3    407071.0  305482.5  165854.5  407071.0  383540.5  305482.5  383540.5   
s_a4    317525.0  207269.5  437496.5  317525.0  234267.5  207269.5  234267.5   
s_a5    350069.0  172189.5  223535.5  350069.0  293468.5  172189.5  293468.5   
t_resi   46294.5  110373.5  111755.0   69909.5   90737.0  116053.5  141166.5   
t_resn   39486.0   80383.5  132640.0  171032.5  171032.5  233629.5  440647.5   
t_ss8    29832.5  165714.5  435089.0  279395.0  111068.0  111068.0  111068.0   
t_rsa    41537.5  396310.0  319658.0  147267.0  167221.5  169978.5  246624.5   
t_up    315215.0   55286.0   17270.0  315215.0  406325.5  102693.0  289946.5   
t_down  197047.5   26694.5  115479.0  197047.5   37809.5  280651.5   91172.5   
t_phi    60280.0  122833.5  445024.0  369415.0   64815.5  114966.5   95479.0   
t_psi   357201.0  277245.0  289150.0   58445.0  427803.5  358037.0  326210.0   
t_ss3   216601.5  216601.5  443698.0  216601.5  216601.5  216601.5  216601.5   
t_a1      3692.0  385346.5  205316.0   49623.5   49623.5   85370.5  274253.5   
t_a2    353297.0   24721.5  437989.0  186896.5  186896.5   97449.5  393460.5   
t_a3    134296.0  302296.5  276890.0  384215.5  384215.5  107929.5  440647.5   
t_a4     30882.0  209201.5  332734.0  236532.5  236532.5  395724.5   58581.5   
t_a5    177809.0  159858.5  415308.0  284406.5  284406.5  122924.5  363764.5   

              9         10        11  
s_resi  106639.5   56274.0  108174.0  
s_resn  135906.5  172071.5  228750.0  
s_ss8   296138.5  296138.5  296138.5  
s_rsa   289245.0   45540.5  352975.0  
s_up     21455.5  223585.5   95565.0  
s_down  253931.5  224092.5  110725.5  
s_phi   292491.5  363692.0  338671.5  
s_psi   184320.5   45278.0   75940.0  
s_ss3   219852.0  219852.0  219852.0  
s_a1    198106.5   49750.5   83967.0  
s_a2    431239.5  176457.5   92799.0  
s_a3    281297.5  383540.5  120294.0  
s_a4    338242.5  234267.5  399305.0  
s_a5    420204.5  293468.5  136419.0  
t_resi   72557.0   30671.5   73880.0  
t_resn  278229.5  375240.5   80383.5  
t_ss8   279395.0   29832.5  279395.0  
t_rsa   385326.5  189251.0  244594.5  
t_up     27736.5  265023.5  241048.0  
t_down  332464.5   69857.0   91172.5  
t_phi   175887.5   85085.5  295833.0  
t_psi   222837.0  338394.5  136846.0  
t_ss3   216601.5  216601.5  216601.5  
t_a1    336677.5  245974.5  385346.5  
t_a2    368451.5  339929.5   24721.5  
t_a3    254279.5  406963.5  302296.5  
t_a4    183479.5  311910.5  209201.5  
t_a5    308941.5  340542.5  159858.5

In [28]:
Y.head(10).T

0     HBOND
1     HBOND
2     HBOND
4     HBOND
5       VDW
6       VDW
8     HBOND
9     HBOND
10    HBOND
11    HBOND
Name: Interaction, dtype: category
Categories (6, object): ['HBOND', 'IONIC', 'PICATION', 'PIPISTACK', 'SSBOND', 'VDW']

In [30]:
def forest_test(X, Y):
    X = X[0:100000]
    Y = Y[0:100000]
    X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, 
                                                        test_size = 0.30, 
                                                        random_state = 101)
    trainedforest = RandomForestClassifier(n_estimators=700).fit(X_Train,Y_Train)
    predictionforest = trainedforest.predict(X_Test)
    print(confusion_matrix(Y_Test,predictionforest))
    print(classification_report(Y_Test,predictionforest))

forest_test(X, Y)



[[16068   163     1   121     1  3282]
 [  333    88     0     0     0    79]
 [    7     0     0     0     0    24]
 [  102     0     0    73     0   438]
 [    1     0     0     0     3    57]
 [ 5235   100    18   392    38  3376]]
              precision    recall  f1-score   support

       HBOND       0.74      0.82      0.78     19636
       IONIC       0.25      0.18      0.21       500
    PICATION       0.00      0.00      0.00        31
   PIPISTACK       0.12      0.12      0.12       613
      SSBOND       0.07      0.05      0.06        61
         VDW       0.47      0.37      0.41      9159

    accuracy                           0.65     30000
   macro avg       0.28      0.26      0.26     30000
weighted avg       0.63      0.65      0.64     30000



In [43]:
def generate_one_hot(df, category):
    lables = []
    for i in range(0, len(df)):
        print(f'value {len(df["Interaction"][i])}')
        input()
        if df['Interaction'][i] == category:
            lables.append(1)
        else:
            lables.append(0)
    return lables

def generate_labels(df):
    category = df['Interaction'].astype('category')
    category = category.cat.categories.tolist()
    lables = {}
    for cat in category:
        lables[cat] = generate_one_hot(df, cat)
    return lables

labels = generate_labels(df)


value 1123


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().